# Generated by Django 5.2.1 on 2025-06-12 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.expensecategory'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='file_path',
            field=models.FileField(upload_to='receipts/'),
        ),
    ]
