# Generated by Django 5.2.1 on 2025-06-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_receipt_category_alter_receipt_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedsms',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
