# Generated by Django 5.2.1 on 2025-06-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_parsedsms_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parsedsms',
            name='date',
        ),
        migrations.AddField(
            model_name='receipt',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
