# Generated by Django 5.2.1 on 2025-06-12 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_parsedsms_date_receipt_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'verbose_name_plural': 'Expense Categories'},
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='category_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='expensecategory',
            unique_together={('user', 'category_name')},
        ),
    ]
