# Generated by Django 5.2.1 on 2025-06-13 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_expensecategory_options_expensecategory_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='reference_id',
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt_reference',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_expense', to='authentication.receipt'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='origin',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('scanned', 'From Receipt Scan')], default='manual', max_length=50),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='scanned_text',
            field=models.TextField(blank=True),
        ),
    ]
