# Generated by Django 5.2.1 on 2025-06-17 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_expense_reference_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='goal',
            name='authenticat_user_id_4e52d8_idx',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='goal_name',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='target_status',
        ),
        migrations.AddField(
            model_name='goal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='goal',
            name='notification_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('reached', 'Reached'), ('failed', 'Failed')], default='in_progress', max_length=20),
        ),
        migrations.AddField(
            model_name='goal',
            name='target_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
