"""
Django settings for cashcarebackend project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from dotenv import load_dotenv

load_dotenv()

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")


import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),  # increase to 30 mins or more
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),     # refresh token expiry
}

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-%)5legz&qn7dhz7_85a2dr7_z2trp2bh(y=j*j$$%86ab)fsh0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*','192.168.1.69']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',     # ✅ This comes after grappelli
    # 'grappelli',                # ✅ MUST come before admin
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'authentication',
    'django_filters',
    'suggestionAI'
]

AUTH_USER_MODEL = 'authentication.CustomUser'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # or another provider
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'artha0819@gmail.com'
EMAIL_HOST_PASSWORD = 'bbqrfuogvbzknamm'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
  
REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.OrderingFilter',
        'rest_framework.filters.SearchFilter',
    ],

    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
    
}

ROOT_URLCONF = 'cashcarebackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates',],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cashcarebackend.wsgi.application'
ALLOWED_HOSTS = ['10.0.2.2', 'localhost', '127.0.0.1','192.168.1.66','192.168.56.1','192.168.1.70','192.168.20.205', '192.168.1.69']


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'arthacashcare',
        'USER': 'postgres',
        'PASSWORD': 'lokraj',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

AUTHENTICATION_BACKENDS = [
    'authentication.backends.EmailBackend',
]

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# settings.py



# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
STATIC_ROOT = BASE_DIR / "staticfiles"

# # settings.py
# # settings.py
# JAZZMIN_SETTINGS = {
#     # "site_title": "Artha Cashcare Dashboard",
#     # "site_header": "Artha Cashcare",
#     # "site_logo": "path/to/your-logo.png",
#     # "site_logo_classes": "img-circle",
#     # "welcome_sign": "Welcome to Artha Cashcare Financial Dashboard",
#     # "copyright": "Artha Cashcare",
#     # "show_ui_builder": True,
    
#     # Visual upgrades
#     "theme": "dark",
#     "dark_mode_theme": "darkly",
#     "navigation_expanded": True,
#     "changeform_format": "carousel",
    
#     # Custom icons
#     "icons": {
#         "auth.user": "fas fa-user-tie",
#         "auth.Group": "fas fa-users",
#         "app.Expenses": "fas fa-money-bill-wave",
#         "app.Incomes": "fas fa-chart-line",
#         "app.Goals": "fas fa-bullseye",
#         "app.Parsed_smss": "fas fa-sms",
#     },
# }

# settings.py
JAZZMIN_SETTINGS = {
    # "site_title": "Artha Cashcare Dashboard",
    # "site_header": "Artha Cashcare",
    # "site_logo": "path/to/your-logo.png",
    # "site_logo_classes": "img-circle",
    # "welcome_sign": "Welcome to Artha Cashcare Financial Dashboard",
    "copyright": "Artha Cashcare",
    # "show_ui_builder": True,
    
    # Visual upgrades
    "theme": "dark",
    "dark_mode_theme": "darkly",
    "navigation_expanded": True,
    "changeform_format": "carousel",
     "site_brand": "Artha",
    
    # Custom icons
   "icons": {
        "auth.Group": "fas fa-users-cog",
        "authentication.CustomUser": "fas fa-user",
        "authentication.Expense": "fas fa-minus-circle",
        "authentication.Income": "fas fa-plus-circle",
        "authentication.Goal": "fas fa-bullseye",
        "authentication.ParsedSMS":"fas fa-envelope-open-text",
    },
    "order_with_respect_to": [
        "authentication",
        "income",
        "expense",
        "goals"
    ],
        "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
    "show_sidebar": True,

}

JAZZMIN_UI_TWEAKS = {
    # "navbar_small_text": True,
    # "footer_small_text": True,    
    # "body_small_text": False,
    # "brand_small_text": True,
    "brand_colour": "navbar-indigo",
    "accent": "accent-primary",
    "navbar": "navbar-indigo navbar-dark",
    "no_navbar_border": False,
    "sidebar": "sidebar-dark-indigo",
    "sidebar_nav_small_text": True,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": True,
    "theme":'simplex'
}